In [1]:
import pandas as pd
import numpy as np

In [2]:
string_data = pd.Series(['aardvark','artichoke',np.nan,'avocado'])

In [3]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [4]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [5]:
string_data[0] = None

In [6]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [7]:
from numpy import nan as NA

In [8]:
data = pd.Series([1,NA,3.5,NA,7])


In [9]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [10]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [11]:
data = pd.DataFrame([[1., 6.5, 3.],[1., NA, NA],[NA, NA, NA],[NA,6.5,3.]])

In [12]:
cleaned = data.dropna()

In [13]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [14]:
cleaned


0    1    2
0  1.0  6.5  3.0

In [15]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [16]:
data[4] = NA

In [17]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [18]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [19]:
df = pd.DataFrame(np.random.randn(7, 3))

In [20]:
df.iloc[:4, 1] = NA

In [21]:
df.iloc[:2, 2] = NA

In [22]:
df


0         1         2
0 -1.717250       NaN       NaN
1  1.606883       NaN       NaN
2 -0.496826       NaN -0.819921
3 -0.230682       NaN  0.064412
4  0.662587 -0.724473  0.441221
5 -0.063567 -0.866038 -2.162148
6 -0.525432  0.968384 -0.734263

In [23]:
df.dropna()

0         1         2
4  0.662587 -0.724473  0.441221
5 -0.063567 -0.866038 -2.162148
6 -0.525432  0.968384 -0.734263

In [24]:
df.dropna(thresh = 2)

0         1         2
2 -0.496826       NaN -0.819921
3 -0.230682       NaN  0.064412
4  0.662587 -0.724473  0.441221
5 -0.063567 -0.866038 -2.162148
6 -0.525432  0.968384 -0.734263

In [25]:
df.fillna(0)

0         1         2
0 -1.717250  0.000000  0.000000
1  1.606883  0.000000  0.000000
2 -0.496826  0.000000 -0.819921
3 -0.230682  0.000000  0.064412
4  0.662587 -0.724473  0.441221
5 -0.063567 -0.866038 -2.162148
6 -0.525432  0.968384 -0.734263

In [26]:
df.fillna({1: 0.5, 2:0})

0         1         2
0 -1.717250  0.500000  0.000000
1  1.606883  0.500000  0.000000
2 -0.496826  0.500000 -0.819921
3 -0.230682  0.500000  0.064412
4  0.662587 -0.724473  0.441221
5 -0.063567 -0.866038 -2.162148
6 -0.525432  0.968384 -0.734263

In [27]:
_ = df.fillna(0, inplace =True)

In [28]:
df

0         1         2
0 -1.717250  0.000000  0.000000
1  1.606883  0.000000  0.000000
2 -0.496826  0.000000 -0.819921
3 -0.230682  0.000000  0.064412
4  0.662587 -0.724473  0.441221
5 -0.063567 -0.866038 -2.162148
6 -0.525432  0.968384 -0.734263

In [29]:
df = pd.DataFrame(np.random.randn(6,3))

In [30]:
df.iloc[2:,1] = NA

In [31]:
df.iloc[4:,2] = NA

In [32]:
df

0         1         2
0  0.602429  0.199009 -0.511978
1 -0.519368 -0.718206  0.095454
2 -0.644496       NaN -0.945304
3 -0.427988       NaN -0.437231
4  1.648101       NaN       NaN
5  1.540565       NaN       NaN

In [33]:
df.fillna(method = 'ffill')

0         1         2
0  0.602429  0.199009 -0.511978
1 -0.519368 -0.718206  0.095454
2 -0.644496 -0.718206 -0.945304
3 -0.427988 -0.718206 -0.437231
4  1.648101 -0.718206 -0.437231
5  1.540565 -0.718206 -0.437231

In [35]:
df.fillna(method = 'ffill',limit=2)

0         1         2
0  0.602429  0.199009 -0.511978
1 -0.519368 -0.718206  0.095454
2 -0.644496 -0.718206 -0.945304
3 -0.427988 -0.718206 -0.437231
4  1.648101       NaN -0.437231
5  1.540565       NaN -0.437231

In [36]:
data = pd.Series([1., NA, 3.5, NA, 7])

In [37]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [38]:
data = pd.DataFrame({'k1':['one','two']*3 + ['two'],'k2':[1,1,2,3,3,4,4]})

In [39]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [40]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [41]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [42]:
data['v1'] = range(7)

In [43]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [44]:
data.drop_duplicates(['k1','k2'],keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [45]:
data = pd.DataFrame({'food':['bacon','pulled pork','bacon','pastrami','corned beef'],'ounces':[4,3,12,6,7.5]})

In [46]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5

In [47]:
meat_to_animal = {'bacon':'pig','pulled pork': 'pig','pastrami':'cow','corned beef':'cow'}

In [48]:
lowercased = data['food'].str.lower()

In [49]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
Name: food, dtype: object

In [50]:
data['animal'] = lowercased.map(meat_to_animal)

In [51]:
data


food  ounces animal
0        bacon     4.0    pig
1  pulled pork     3.0    pig
2        bacon    12.0    pig
3     pastrami     6.0    cow
4  corned beef     7.5    cow

In [53]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0    pig
1    pig
2    pig
3    cow
4    cow
Name: food, dtype: object

In [54]:
data = pd.Series([1.,-999.,2.,-999.,-1000.,3.])

In [55]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [56]:
data.replace([-999,-1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [57]:
data.replace([-999,-1000],[np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [58]:
data.replace({-999:np.nan, -1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [59]:
data = pd.DataFrame(np.arange(12).reshape((3,4)), index=['ohio','colorado','new york',],columns=['one','two','three','four'])

In [60]:
data


one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
new york    8    9     10    11

In [61]:
transform = lambda x: x[:4].upper()

In [62]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [63]:
data.index = data.index.map(transform)

In [64]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [65]:
data.rename(index=str.title, columns =str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [1]:
data.rename(index={'OHIO':'INDIANA'}, inplace = True)

NameError: name 'data' is not defined

In [2]:
data


NameError: name 'data' is not defined

In [5]:
import numpy as np
import pandas as pd
data = pd.DataFrame(np.arange(12).reshape((3,4)), index=['ohio','colorado','new york',],columns=['one','two','three','four'])

In [6]:
data 


one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
new york    8    9     10    11

In [8]:
ages = [20,22,25,27,21,23,37,31,61,45,41,32]

In [9]:
bins = [18,25,35,60,100]

In [10]:
cats = pd.cut(ages,bins)

In [11]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [12]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [1]:
cats.categories

NameError: name 'cats' is not defined

In [2]:
import numpy as np
import pandas as pd

In [3]:
data = np.random.rand(20)

In [5]:
pd.cut(data, 4, precision = 2)

[(0.78, 0.98], (0.78, 0.98], (0.78, 0.98], (0.57, 0.78], (0.78, 0.98], ..., (0.36, 0.57], (0.15, 0.36], (0.36, 0.57], (0.15, 0.36], (0.78, 0.98]]
Length: 20
Categories (4, interval[float64]): [(0.15, 0.36] < (0.36, 0.57] < (0.57, 0.78] < (0.78, 0.98]]

In [6]:
data = np.random.randn(1000) 

In [7]:
cats = pd.qcut(data, 4)

In [8]:
cats

[(0.657, 3.314], (0.0998, 0.657], (-0.661, 0.0998], (0.657, 3.314], (0.0998, 0.657], ..., (-0.661, 0.0998], (-2.9179999999999997, -0.661], (-0.661, 0.0998], (0.0998, 0.657], (-0.661, 0.0998]]
Length: 1000
Categories (4, interval[float64]): [(-2.9179999999999997, -0.661] < (-0.661, 0.0998] < (0.0998, 0.657] < (0.657, 3.314]]

In [9]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(0.0998, 1.252], (0.0998, 1.252], (-1.237, 0.0998], (1.252, 3.314], (0.0998, 1.252], ..., (-1.237, 0.0998], (-1.237, 0.0998], (-1.237, 0.0998], (0.0998, 1.252], (-1.237, 0.0998]]
Length: 1000
Categories (4, interval[float64]): [(-2.9179999999999997, -1.237] < (-1.237, 0.0998] < (0.0998, 1.252] < (1.252, 3.314]]

In [10]:
data = pd.DataFrame(np.random.randn(1000, 4))

In [11]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.020408    -0.019992    -0.009913    -0.092502
std       1.009597     0.955881     0.973067     1.019829
min      -3.181894    -2.772381    -2.677403    -2.805052
25%      -0.714022    -0.656233    -0.715593    -0.780775
50%      -0.072453    -0.012082    -0.018450    -0.119911
75%       0.694492     0.582138     0.640244     0.623157
max       3.361702     2.764768     3.507950     3.180061

In [12]:
col = data[2]

In [13]:
col = data[2]
col[np.abs(col)>3]

432    3.076968
498    3.069965
694    3.507950
Name: 2, dtype: float64

In [14]:
data[(np.abs(data)>3).any(1)]

0         1         2         3
331  3.361702 -0.741380 -1.646909 -0.313425
432 -0.043109  1.095843  3.076968 -0.739277
498  0.432489 -0.746754  3.069965 -0.200094
631  3.238219  0.194947  0.136197  0.952843
694 -0.190845 -0.526503  3.507950  0.379282
733  0.481813 -0.055339  0.822556  3.180061
787 -3.181894 -0.444733  0.301252  0.583110
982  3.265481 -1.476081 -2.144172 -0.142554

In [15]:
data[np.abs(data)>3] = np.sign(data)*3


In [1]:
data.describe()

NameError: name 'data' is not defined

In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
df = pd.DataFrame(np.arange(5*4).reshape((5,4)))

In [5]:
sampler = np.random.permutation(5)

In [6]:
sampler

array([3, 1, 2, 4, 0])

In [7]:
array([3,1,4,2,0])

NameError: name 'array' is not defined

In [8]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [9]:
df.take(sampler)

0   1   2   3
3  12  13  14  15
1   4   5   6   7
2   8   9  10  11
4  16  17  18  19
0   0   1   2   3

In [10]:
df.sample(n=3)

0   1   2   3
4  16  17  18  19
1   4   5   6   7
0   0   1   2   3

In [11]:
choices = pd.Series([5, 7,-1, 6,4])

In [12]:
draws = choices.sample(n=10, replace=True)

In [13]:
draws

1    7
0    5
2   -1
3    6
2   -1
3    6
2   -1
3    6
2   -1
4    4
dtype: int64

In [14]:
val = 'a,b,guido'

In [15]:
val.split(',')

['a', 'b', 'guido']

In [18]:
pieces = [x.strip() for x in val.split(',')]

In [19]:
pieces

['a', 'b', 'guido']

In [20]:
first,second,third = pieces


In [21]:
first + '::' + second + '::' + third

'a::b::guido'

In [22]:
import re