In [1]:
import numpy as py
import pandas as pd

In [2]:
data = pd.Series(np.random.randn(9),index=[['a','a','a','b','b','c','c','d','d'],[1, 2, 3, 1, 3,1,2,2,3]])

In [3]:
data


a  1   -1.223793
   2   -1.145188
   3   -0.311819
b  1    1.409559
   3   -0.350422
c  1    0.205265
   2   -0.881930
d  2   -0.557613
   3    0.109224
dtype: float64

In [4]:
data.index

MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3]],
           codes=[[0, 0, 0, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 2, 0, 1, 1, 2]])

In [5]:
data['b']

1    1.409559
3   -0.350422
dtype: float64

In [6]:
data['b':'c']

b  1    1.409559
   3   -0.350422
c  1    0.205265
   2   -0.881930
dtype: float64

In [7]:
data.loc[['b', 'd']]

b  1    1.409559
   3   -0.350422
d  2   -0.557613
   3    0.109224
dtype: float64

In [9]:
data.loc[:,2]

a   -1.145188
c   -0.881930
d   -0.557613
dtype: float64

In [10]:
data.unstack()

1         2         3
a -1.223793 -1.145188 -0.311819
b  1.409559       NaN -0.350422
c  0.205265 -0.881930       NaN
d       NaN -0.557613  0.109224

In [11]:
data.unstack().stack()

a  1   -1.223793
   2   -1.145188
   3   -0.311819
b  1    1.409559
   3   -0.350422
c  1    0.205265
   2   -0.881930
d  2   -0.557613
   3    0.109224
dtype: float64

In [12]:
frame = pd.DataFrame(np.arange(12).reshape((4,3)))

In [13]:
frame

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [14]:
frame.swaplevel('key1','key2')

AttributeError: 'RangeIndex' object has no attribute 'swaplevel'

In [15]:
frame = pd.DataFrame({'a':range(7), 'b':range(7, 0, -1),'c':['one','one','one','two','two']})

ValueError: arrays must all be same length

In [16]:
df1 = pd.DataFrame({'key':['b','b','a','c','a','a','b'],'data1':range(7)})

In [17]:
df2 = pd.DataFrame({'key':['a','b','d'],'data2':range(3)})

In [18]:
df1


key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [19]:
df2

key  data2
0   a      0
1   b      1
2   d      2

In [20]:
pd.merge(df1,df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [21]:
pd.merge(df1,df2,on='key')

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [22]:
pd.merge(df1,df2,how='outer')

key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0

In [23]:
pd.merge(df1,df2,how='inner')

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [24]:
left1 = pd.DataFrame({'key':['a','b','a','a','b','c'],'value':range(6)})

In [25]:
right1 = pd.DataFrame({'group_val':[3.5, 7]},index=['a','b'])

In [26]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [27]:
right1


group_val
a        3.5
b        7.0

In [28]:
pd.merge(left1, right1, left_on = 'key', right_index = True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [29]:
pd.merge(left1, right1, left_on = 'key',right_index = True,how='outer')

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [30]:
arr = np.arange(12).reshape((3,4))

In [31]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
np.concatenate([arr,arr], axis =1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [33]:
s1 =pd.Series([0,1],index=['a','b'])

In [34]:
s2 = pd.Series([2,3,4],index=['c','d','e'])

In [35]:
s3 = pd.Series([5,6],index=['f','g'])

In [36]:
pd.concat([s1,s2,s3])



a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [38]:
pd.concat([s1,s2,s3],axis=1)

d:\python3.7\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [39]:
s4 = pd.concat([s1, s3])

In [40]:
s4


a    0
b    1
f    5
g    6
dtype: int64

In [41]:
pd.concat([s1,s4],axis=1)

d:\python3.7\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0  1
a  0.0  0
b  1.0  1
f  NaN  5
g  NaN  6

In [42]:
pd.concat([s1,s4],axis=1,join_axes=[['a','c','b','e']])

0    1
a  0.0  0.0
c  NaN  NaN
b  1.0  1.0
e  NaN  NaN

In [43]:
result = pd.concat([s1,s1,s3],keys=['one','two','three'])

In [44]:
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [45]:
result.unstack()

a    b    f    g
one    0.0  1.0  NaN  NaN
two    0.0  1.0  NaN  NaN
three  NaN  NaN  5.0  6.0

In [46]:
pd.concat([s1,s2,s3],axis=1,keys=['one','two','three'])

d:\python3.7\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [47]:
df1 = pd.DataFrame(np.arange(6).reshape(3,2),index=['a','b','c'],columns=['one','two'])

In [48]:
df2 = pd.DataFrame(5 + np.arange(4).reshape(2,2),index=['a','c'],columns=['three','four'])

In [49]:
df1


one  two
a    0    1
b    2    3
c    4    5

In [50]:
df2

three  four
a      5     6
c      7     8

In [51]:
pd.concat({'level1':df1, 'level2':df2}, axis=1)

d:\python3.7\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [52]:
df1 = pd.DataFrame(np.random.randn(3,4),columns=['a','b','c','d'])

In [53]:
df2 = pd.DataFrame(np.random.randn(2,3),columns=['b','d','a'])

In [54]:
df1


a         b         c         d
0  0.243914 -0.215295  0.968609  0.502394
1  0.588143  0.835310  0.033238 -1.009437
2  0.604472  2.249883  1.616395  0.959486

In [55]:
df2

b         d         a
0 -0.403304 -0.853946  1.966686
1 -0.125742 -1.463039 -0.726800

In [56]:
pd.concat([df1,df2],ignore_index=True)

d:\python3.7\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


a         b         c         d
0  0.243914 -0.215295  0.968609  0.502394
1  0.588143  0.835310  0.033238 -1.009437
2  0.604472  2.249883  1.616395  0.959486
3  1.966686 -0.403304       NaN -0.853946
4 -0.726800 -0.125742       NaN -1.463039

In [57]:
a = pd.Series([np.nan,2.5,np.nan,3.5,4.5,np.nan],index=['f','e','d','c','b','a'])

In [58]:
b = pd.Series(np.arange(len(a),dtype = np.float64),index=['f','e','d','c','b','a'])

In [59]:
b[-1] = np.nan

In [60]:
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [61]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

In [62]:
np.where(pd.isnull(a),b,a)

array([0. , 2.5, 2. , 3.5, 4.5, nan])

In [63]:
b[:-2].combine_first(a[2:])

a    NaN
b    4.5
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

In [64]:
s1 = pd.Series([0,1,2,3],index=['a','b','c','d'])

In [65]:
s2 = pd.Series([4,5,6],index=['c','d','e'])

In [66]:
s1

a    0
b    1
c    2
d    3
dtype: int64

In [67]:
s2

c    4
d    5
e    6
dtype: int64

In [68]:
data2 =pd.concat([s1,s2],keys=['one','two'])

In [69]:
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: int64

In [70]:
data2.unstack()

a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0

In [71]:
data2.unstack()

a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0

In [72]:
data2.unstack().stack()

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
two  c    4.0
     d    5.0
     e    6.0
dtype: float64

In [74]:
df = pd.DataFrame({'left':result, 'right':result+5},columns=pd.Index(['left','right'],name = 'side'))

In [75]:
df

side     left  right
one   a     0      5
      b     1      6
two   a     0      5
      b     1      6
three f     5     10
      g     6     11

In [76]:
df.unstack('state')

KeyError: 'Level state not found'

In [80]:
periods = pd.PeriodIndex(year=data.year,quarter=data.quarter,name='date')

AttributeError: 'Series' object has no attribute 'year'

In [81]:
df = pd.DataFrame({'key':['foo','bar','baz'],'A':[1,2,3],'B':[4,5,6],'C':[7,8,9]})

In [82]:
df

key  A  B  C
0  foo  1  4  7
1  bar  2  5  8
2  baz  3  6  9

In [83]:
melted =pd.melt(df,['key'])

In [84]:
melted

key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6
6  foo        C      7
7  bar        C      8
8  baz        C      9

In [85]:
reshaped = melted.pivot('key','variable','value')

In [86]:
reshaped

variable  A  B  C
key              
bar       2  5  8
baz       3  6  9
foo       1  4  7

In [87]:
reshaped.reset_index()

variable  key  A  B  C
0         bar  2  5  8
1         baz  3  6  9
2         foo  1  4  7

In [88]:
pd.melt(df, id_vars=['key'],value_vars=['A','B'])

key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6

In [89]:
pd.melt(df, value_vars=['A','B','C'])

variable  value
0        A      1
1        A      2
2        A      3
3        B      4
4        B      5
5        B      6
6        C      7
7        C      8
8        C      9

In [90]:
pd.melt(df,value_vars=['keys','A','B'])

KeyError: "The following 'value_vars' are not present in the DataFrame: ['keys']"